name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Correction de la majuscule ici : ArtemSerebriakov
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug

      - name: Upload APK
        # Version v4 obligatoire en 2026
        uses: actions/upload-artifact@v4
        with:
          name: MonAppChips-APK
          path: bin/*.apk
