name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MonAppChips-APK
          path: bin/*.apk
